### ISSUE TITLE
二维码失效

### ISSUE THREAD

**Issue by Crescentz** [sty945/bank_interview#3]
二维码失效

**Comment by sty945** [comment]
这篇文章里也有二维码[中国交通银行总行软件开发中心拿offer流程](https://blog.csdn.net/sty945/article/details/101347777)

**Comment by Crescentz** [comment]
买了，然后里面介绍的笔试连接又跑回了这里， 所以这里是全部的笔试题目。。。没有更多的了么，还以为GITCHAT里有更详细的笔试资料

**Comment by sty945** [comment]
这是我当时的笔试复习资料，gitchat主要是更详细的介绍。笔试资料更多的话，也可以刷一刷牛客之类的平台，但是可能太多了刷起来比较耽误时间

**Comment by H-YunHui** [comment]
@sty945
我试过多种下载方式，下载的文件都是损坏的，能不能更新下或者以百度云方式分享？
