### ISSUE TITLE
Hibernate这种老掉牙的也会考吗

### ISSUE THREAD

**Issue by cxt1998sy** [sty945/bank_interview#4]
还有那些jsp啥的题目也会出的啊  其他感觉蛮正常的 多谢分享

**Comment by sty945** [comment]
![image](https://user-images.githubusercontent.com/10708326/87854826-0f03f500-c947-11ea-91bc-754a9276b254.png)

[新闻链接](https://www.jiqizhixin.com/articles/2020-04-19-2)

看了这个新闻你会发现在银行里`Hibernate`、`JSP` 并不老。
